### ISSUE TITLE
Combine bounty related commands into /bounty

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/BountyBot#3]
Using sub-commands, bounty related commands can be organized to be shown together. Relevant commands include:
- [x] #2 - /bounty post
- [ ] #4 - /bounty edit
- [ ] #5 - /bounty add-completer
- [ ] #6 - /bounty remove-completer
- [ ] #7 - /bounty complete
- [ ] #8 - /bounty take-down

**Comment by ntseng** [comment]
Subcommand structure is set up as of #2
